### ISSUE TITLE
db.r4.* instances not available

### ISSUE THREAD

**Issue by pjr** [getstrake/aws-pricing-sheets-addon#18]
It looks like even through the db.r4.* instances are available via the Pricing API that these are not available via this plugin.
```

$ curl -s https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonRDS/current/index.json | grep -c "per db.r4.4xlarge.*Aurora MySQL"
7
```

db.r5.* all seem to be available.

<img width="471" alt="Screenshot 2020-08-12 at 22 23 46" src="https://user-images.githubusercontent.com/46494/90069649-803a8c00-dcea-11ea-92ee-10c857f88102.png">

not sure if this is a limitation or a bug?

**Comment by aryounce** [comment]
@pjr We believe this has been addressed. Please [try the new version of the add-on](https://workspace.google.com/marketplace/app/aws_pricing_by_strake/378787760903) and let us know if you encounter any problems.

**Comment by pjr** [comment]
I'm afraid I'm not close to this anymore to test although I appreciate the work on it! Sorry I can't help confirm
